<?php
  return [
    'USD' => 'USD (United States Dollar)',
    'AUD' => 'AUD (Australian Dollar)',
    'EUR' => 'EUR (Euro)',
    'CAD' => 'CAD (Canadian Dollar)',
    'GBP' => 'GBP (Pound Sterling)',
    'AED' => 'AED (UAE Dirham)',
    'BRL' => 'BRL (Brazilian Real)',
    'CHF' => 'CHF (Swiss Franc)',
    'CLP' => 'CLP (Chilean Peso)',
    'CNY' => 'CNY (Renminbi)',
    'COP' => 'COP (Colombian Peso)',
    'CZK' => 'CZK (Czech Koruna)',
    'DKK' => 'DKK (Danish Krone)',
    'HKD' => 'HKD (Hong Kong Dollar)',
    'HUF' => 'HUF (Hungarian Forint)',
    'IDR' => 'IDR (Indonesian Rupiah)',
    'ILS' => 'ILS (Israeli New Shekel)',
    'INR' => 'INR (Indian Rupee)',
    'JPY' => 'JPY (Japanese Yen)',
    'KRW' => 'KRW (South Korean Won)',
    'MXN' => 'MXN (Mexican Peso)',
    'MYR' => 'MYR (Malaysian Ringgit)',
    'NOK' => 'NOK (Norwegian Krone)',
    'NZD' => 'NZD (New Zealand Dollar)',
    'PHP' => 'PHP (Philippine Peso)',
    'PLN' => 'PLN (Polish Złoty)',
    'RON' => 'RON (Romanian Leu)',
    'RUB' => 'RUB (Russian Ruble)',
    'SAR' => 'SAR (Saudi Riyal)',
    'SEK' => 'SEK (Swedish Krona)',
    'SGD' => 'SGD (Singapore Dollar)',
    'THB' => 'THB (Thai Baht)',
    'TRY' => 'TRY (Turkish Lira)',
    'TWD' => 'TWD (New Taiwan Dollar)',
    'ZAR' => 'ZAR (South African Rand)',
  ];
